spring:
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
      file-size-threshold: 0
  datasource:
    #sqlserver连接
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DatabaseName=Web_CSGO
    username: sa
    password: root
  # 模板引擎
  thymeleaf:
    encoding: utf-8
    # 禁用缓存
    cache: false
    suffix: .html
    mode: LEGACYHTML5
    #模板路径
    #prefix: classpath:/templates/
  freemarker:
    template-loader-path: classpath:/templates/
  #mvc:
   # static-path-pattern: /static/**
 # resources:
    #static-locations: classpath:/static

server:
  port: 8986
  tomcat:
    uri-encoding: utf-8
    max-threads: 200
    min-spare-threads: 10

  # 应用的访问路径
  servlet:
    context-path: /
mybatis-plus:
  type-aliases-package: com.Web_CSGO.mapper.*  #扫描实体类
  mapper-locations: classpath*:/mapping/*Mapper.xml #mapper.xml的位置
  global-config:
      #刷新mapper 调试神器
      db-config:
        #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        id-type: AUTO
        #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#        field-strategy: not_empty
        field-strategy: 1
        #驼峰下划线转换
        column-underline: true
        #数据库大写下划线转换
        #capital-mode: true
        #逻辑删除配置
        logic-delete-value: 1
        logic-not-delete-value: 0
        db-type: sql_server
      refresh: true
  config-location: classpath:mybatis-config.xml

#日志输出
logging:
  level:
    com.Web_CSGO.mapper: debug


